catalogs:
  # ===== BUILD TOOLS =====
  build:
    # Vite & Build Tools
    vite: ^6.4.1
    "@vitejs/plugin-react": ^4.5.0
    vite-plugin-pwa: ^1.0.0
    vite-tsconfig-paths: ^5.1.4

    # MDX & Content Processing
    "@mdx-js/rollup": ^3.1.0

    # Tailwind CSS Build
    "@tailwindcss/vite": ^4.1.18

  # ===== DEVELOPMENT TOOLS =====
  dev:
    # TypeScript & Compilation
    typescript: ~5.8.3

    # Routing Development
    "@tanstack/router-plugin": ^1.120.11

    # Content Processing
    unified: ^11.0.5

  # ===== LINTING & FORMATTING =====
  lint:
    # Biome (ESLint/Prettier Alternative)
    "@biomejs/biome": ^1.9.4

    # Commit Linting
    "@commitlint/cli": ^19.8.1
    "@commitlint/config-conventional": ^19.8.1
    "@commitlint/types": ^19.8.1

    # Git Hooks
    husky: ^9.1.7

  # ===== FRONTEND CORE =====
  prod:
    # React & Core
    react: ^19.1.0
    react-dom: ^19.1.0

    # Routing
    "@tanstack/react-router": ^1.120.11
    "@tanstack/react-router-devtools": ^1.120.11

    # Forms & Validation
    react-hook-form: ^7.56.4
    "@hookform/resolvers": ^5.2.2

    # UI Components & Libraries
    "@radix-ui/react-dropdown-menu": ^2.1.16
    "@radix-ui/react-label": ^2.1.8
    "@radix-ui/react-slot": ^1.2.4
    "@radix-ui/react-tooltip": ^1.2.8

    # Theming
    next-themes: ^0.4.6

    # Notifications
    sonner: ^2.0.3

    # Content Processing
    remark-directive: ^4.0.0
    remark-directive-rehype: ^0.4.2
    unist-util-visit: ^5.0.0

  # ===== ICONS =====
  icons:
    lucide-react: ^0.511.0

  # ===== STYLING =====
  style:
    # Tailwind CSS
    tailwindcss: ^4.1.18
    tailwind-merge: ^3.3.0

    # Animation
    tw-animate-css: ^1.3.0

  # ===== UTILITIES =====
  utils:
    # Class & Style Utilities
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1

    # Validation
    zod: ^3.25.30

  # ===== TYPE DEFINITIONS =====
  types:
    # Node & Core Types
    "@types/node": ^24.10.4
    "@types/react": ^19.1.5
    "@types/react-dom": ^19.1.5

    # Content Types
    "@types/mdast": ^4.0.4
    "@types/mdx": ^2.0.13

onlyBuiltDependencies:
  - "@biomejs/biome"
  - "@tailwindcss/oxide"
  - esbuild
