blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Discuss a Topic
    url: https://github.com/ryuudotgg/search/discussions
    about: Ask questions or discuss topics related to Ryuu's Search with other users.
  - name: Feature / Documentation Request
    url: https://github.com/ryuudotgg/search/discussions/new?category=ideas
    about: You may open a feature or documentation request in discussions.
