import type { Bang } from "./index";

export const customBangs: Bang[] = [
  {
    c: "AI",
    d: "chatgpt.com",
    r: 0,
    s: "ChatGPT",
    sc: "AI",
    t: "chatgpt",
    u: "https://chatgpt.com/?prompt={{{s}}}",
  },
  {
    c: "AI",
    d: "claude.ai",
    r: 0,
    s: "Claude",
    sc: "AI",
    t: "claude",
    u: "https://claude.ai/new?q={{{s}}}",
  },
  {
    c: "AI",
    d: "t3.chat",
    r: 0,
    s: "T3 Chat",
    sc: "AI",
    t: "t3",
    u: "https://t3.chat/new?q={{{s}}}",
  },
  {
    c: "AI",
    d: "www.perplexity.ai",
    r: 0,
    s: "Perplexity",
    sc: "AI",
    t: "perplexity",
    u: "https://www.perplexity.ai/search?q={{{s}}}",
  },
  {
    c: "AI",
    d: "huggingface.co",
    r: 0,
    s: "Hugging Face",
    sc: "AI",
    t: "hf",
    u: "https://huggingface.co/search/full-text?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "npmx.dev",
    r: 0,
    s: "npmx",
    sc: "Programming",
    t: "npmx",
    u: "https://npmx.dev/search?q={{{s}}}",
  },
  {
    c: "Tech",
    d: "regex101.com",
    r: 0,
    s: "regex101",
    sc: "Programming",
    t: "regex101",
    u: "https://regex101.com/?regex={{{s}}}",
  },
  {
    c: "Online Services",
    d: "kagi.com",
    r: 0,
    s: "Kagi",
    sc: "Search",
    t: "kagi",
    u: "https://kagi.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "www.tiktok.com",
    r: 0,
    s: "TikTok",
    sc: "Social",
    t: "tiktok",
    u: "https://www.tiktok.com/search?q={{{s}}}",
  },
  {
    c: "Online Services",
    d: "bsky.app",
    r: 0,
    s: "Bluesky",
    sc: "Social",
    t: "bsky",
    u: "https://bsky.app/search?q={{{s}}}",
  },
];
