// Generates src/lib/common-bangs.ts (the bangs inlined for instant redirects).
//
// Every tag in ALLOWLIST is resolved from the merged table (src/lib/bangs.ts),
// so inline behavior always matches the React fallback. NAME_OVERRIDES tidies a
// couple of display names; the first SEARCH_ENGINE_TAGS power the options-popup
// default-engine dropdown and must stay a fixed set.
//
// Re-run after editing the list:  bun scripts/pick-common-bangs.ts

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { bangs } from "../src/lib/bangs";

interface Bang {
  n?: string;
  d: string;
  u: string;
  t: string;
  a?: string[];
}

const SEARCH_ENGINE_TAGS = [
  "ddg",
  "g",
  "bing",
  "brave",
  "kagi",
  "startpage",
  "ecosia",
  "yandex",
  "y",
];

const NAME_OVERRIDES: Record<string, string> = {
  brave: "Brave",
  yandex: "Yandex",
};

const ALLOWLIST: string[] = [
  // Search Engines
  "ddg",
  "g",
  "bing",
  "brave",
  "kagi",
  "startpage",
  "ecosia",
  "yandex",
  "y",

  // AI Assistants
  "chatgpt",
  "claude",
  "t3",
  "perplexity",
  "hf",

  // Search Verticals
  "image",

  // Reference / Dictionaries
  "w",
  "wa",
  "wt",
  "define",
  "ud",
  "mw",
  "thesaurus",
  "imdb",
  "scholar",
  "wayback",
  "gb",
  "gr",

  // Development
  "gh",
  "so",
  "npm",
  "npmx",
  "mdn",
  "caniuse",
  "pypi",
  "crates",
  "rust",
  "py",
  "cpp",
  "php",
  "devdocs",
  "dh",
  "aw",
  "aur",
  "nixpkgs",
  "hn",
  "gitlab",
  "codepen",
  "regex101",

  // Media / Video / Music
  "yt",
  "vimeo",
  "spotify",
  "sc",
  "twitch",
  "nf",
  "tmdb",
  "rt",
  "genius",
  "ytm",
  "lb",
  "al",
  "mal",
  "da",
  "f",

  // Games
  "steam",

  // Shopping
  "a",
  "e",
  "etsy",
  "walmart",
  "ali",
  "target",
  "newegg",
  "bestbuy",
  "zillow",

  // Social
  "reddit",
  "x",
  "tw",
  "fb",
  "ig",
  "li",
  "p",
  "tumblr",
  "discord",
  "tiktok",
  "bsky",

  // Maps
  "maps",
  "osm",

  // Productivity
  "gmail",
  "gt",
  "deepl",
  "drive",
  "gcal",
  "gd",
  "gi",
  "protonmail",

  // News
  "gn",
  "bbc",
  "nyt",
  "reuters",
  "guardian",
  "ap",
];

const clean = (b: Bang): Bang => ({
  n: b.n?.trim() || undefined,
  d: b.d.trim(),
  u: b.u.trim(),
  t: b.t.trim(),
  a: b.a?.length ? b.a : undefined,
});

const byTag = new Map<string, (typeof bangs)[number]>();
for (const b of bangs) {
  byTag.set(b.t, b);
  for (const alias of b.a ?? []) byTag.set(alias, b);
}

const result: Bang[] = [];

const seen = new Set<string>();
const missing = new Set<string>();

for (const tag of ALLOWLIST) {
  if (seen.has(tag)) continue;

  const entry = byTag.get(tag);
  if (!entry?.d) {
    missing.add(tag);
    continue;
  }

  seen.add(tag);
  result.push(
    clean({ n: NAME_OVERRIDES[tag] ?? entry.s, d: entry.d, u: entry.u, t: entry.t, a: entry.a }),
  );
}

if (missing.size) console.error(`Missing Tags: ${Array.from(missing).join(", ")}`);

const entries = result
  .map((b) => {
    const a = b.a?.length ? `, a: ${JSON.stringify(b.a)}` : "";
    return `  { n: ${JSON.stringify(b.n)}, d: ${JSON.stringify(b.d)}, u: ${JSON.stringify(b.u)}, t: ${JSON.stringify(b.t)}${a} },`;
  })
  .join("\n");

const tags = SEARCH_ENGINE_TAGS.map((t) => JSON.stringify(t)).join(", ");
const file = `// @see https://duckduckgo.com/bang.js
// @note generated by scripts/pick-common-bangs.ts; edit the lists there, not this file.

export interface Bang {
  n?: string; // Display Name
  d: string; // Domain
  u: string; // URL Template
  t: string; // Tag/Shortcut
  a?: string[]; // Alias tags
}

export const commonBangs: Bang[] = [
${entries}
];

const SEARCH_ENGINE_TAGS = new Set([${tags}]);
export const searchEngines: Bang[] = commonBangs.filter((bang) => SEARCH_ENGINE_TAGS.has(bang.t));
`;

const outPath = fileURLToPath(new URL("../src/lib/common-bangs.ts", import.meta.url));
writeFileSync(outPath, file);

console.log(`Done.`);
process.exit(0);
