// Generates src/lib/ddg-bangs.ts from the canonical DDG bang list, with our
// fixes baked in: https upgrades, URL_OVERRIDES for stale/nonsensical URLs, a
// domain + absolute URL for DDG-native bangs, filled {inputEncoding} vars, and
// byte-identical URLs merged into one bang with `a` aliases.
//
// Run to sync with upstream:  bun scripts/refresh-ddg-bangs.ts

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE = "https://duckduckgo.com/bang.js";

const PRIMARY_OVERRIDES = new Set(["maps", "bing", "reddit", "define", "devdocs", "ecosia"]);
const URL_OVERRIDES: Record<string, { d: string; u: string }> = {
  startpage: { d: "www.startpage.com", u: "https://www.startpage.com/sp/search?query={{{s}}}" },
  yandex: { d: "yandex.com", u: "https://yandex.com/search/?text={{{s}}}" },
  gm: { d: "google.com", u: "https://google.com/maps?q={{{s}}}" },
};

interface RawBang {
  c?: string;
  d?: string;
  r: number;
  s: string;
  sc?: string;
  t: string;
  u: string;
  a?: string[];
}

const res = await fetch(SOURCE, { headers: { "user-agent": "Mozilla/5.0" } });
if (!res.ok) throw new Error(`Fetch Failed: ${res.status}`);

const raw = (await res.json()) as RawBang[];
const cleaned = raw.map((b): RawBang => {
  let { d, sc, u } = b;
  u = u.replace("{inputEncoding}", "UTF-8");

  const override = URL_OVERRIDES[b.t];
  if (override) {
    d = override.d;
    u = override.u;
  }

  // DDG-native bangs: no domain + a relative URL that resolves on duckduckgo.com.
  if (!d) {
    d = "duckduckgo.com";
    sc = "Search (DDG)";
    if (u.startsWith("/")) u = `https://duckduckgo.com${u}`;
  }

  // Prefer https everywhere (upgrade the scheme, leave embedded URLs alone).
  u = u.replace(/^http:\/\//, "https://");

  return { c: b.c, d, r: b.r, s: b.s, sc, t: b.t, u };
});

// Merge byte-identical URLs into one bang. The highest-relevance tag (or a
// PRIMARY_OVERRIDES pick) becomes `t`; the rest become sorted `a` aliases.
const byUrl = new Map<string, RawBang[]>();
for (const b of cleaned) {
  const group = byUrl.get(b.u);
  if (group) group.push(b);
  else byUrl.set(b.u, [b]);
}

const merged = [...byUrl.values()]
  .map((group): RawBang => {
    const preferred = group.filter((b) => PRIMARY_OVERRIDES.has(b.t));

    const pool = preferred.length ? preferred : group;
    const primary = pool.reduce((best, b) =>
      b.r > best.r || (b.r === best.r && b.t < best.t) ? b : best,
    );

    const aliases = group
      .filter((b) => b.t !== primary.t)
      .map((b) => b.t)
      .sort();

    return aliases.length ? { ...primary, a: aliases } : primary;
  })
  // Highest relevance first, then alphabetical within ties.
  .sort((a, b) => b.r - a.r || a.t.localeCompare(b.t));

const serialize = (b: RawBang): string => {
  const parts: string[] = [];

  if (b.c !== undefined) parts.push(`c: ${JSON.stringify(b.c)}`);

  parts.push(`d: ${JSON.stringify(b.d)}`);
  parts.push(`r: ${b.r}`);
  parts.push(`s: ${JSON.stringify(b.s)}`);

  if (b.sc !== undefined) parts.push(`sc: ${JSON.stringify(b.sc)}`);

  parts.push(`t: ${JSON.stringify(b.t)}`);

  if (b.a !== undefined) parts.push(`a: ${JSON.stringify(b.a)}`);

  parts.push(`u: ${JSON.stringify(b.u)}`);

  return `  { ${parts.join(", ")} },`;
};

const file = `// @see https://duckduckgo.com/bang.js
// @note generated by scripts/refresh-ddg-bangs.ts; do not hand-edit.

import type { Bang } from "./bangs";

export const ddgBangs: Bang[] = [
${merged.map(serialize).join("\n")}
];
`;

const outPath = fileURLToPath(new URL("../src/lib/ddg-bangs.ts", import.meta.url));
writeFileSync(outPath, file);

console.log(`Done.`);
process.exit(0);
