name: CI

on:
  pull_request:
    branches: ["*"]

  push:
    branches: ["main"]

  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  DO_NOT_TRACK: true

jobs:
  lint:
    name: Lint / Format
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Lint / Format
        run: pnpm check
