name: Lock Threads

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    name: Lock Threads
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ryuudotgg'

    steps:
      - uses: dessant/lock-threads@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          add-issue-labels: "locked"
          add-pr-labels: "locked"

          pr-inactive-days: 14

          issue-inactive-days: 14
          issue-comment: "This closed issue has been automatically locked because it had no new activity for 2 weeks. If you are running into a similar issue, please create a new issue with the steps to reproduce. Thank you."

          log-output: true
