name: Snyk

on:
  pull_request:
    branches: ["*"]

  push:
    branches: ["main" ]

  merge_group:

permissions:
  contents: read

jobs:
  snyk:
    name: Security Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    environment: Code Scanning
    env:
      SNYK_ORG: ${{ secrets.SNYK_ORG }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Snyk CLI
        uses: snyk/actions/setup@9adf32b1121593767fc3c057af55b55db032dc04

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: Set Snyk Organization
        run: snyk config set org=$SNYK_ORG

      - name: Run Code Scan
        run: snyk code test --all-projects --sarif > snyk.sarif

      - name: Run Monitor
        run: snyk monitor --all-projects

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif
