name: Triage Issues

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]

permissions:
  issues: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  triage:
    name: Nissuer
    runs-on: ubuntu-latest

    steps:
      - uses: balazsorban44/nissuer@1.10.0
        with:
          comment-unhelpful-weight: 0.5
          reproduction-comment: ".github/comments/invalid-reproduction.md"
          reproduction-invalid-label: "missing reproduction"
          label-comments: |
            {
              "good first issue": ".github/comments/good-first-issue.md",
              "resolved": ".github/comments/resolved.md"
            }
